package com.ekart.user.utility;

public enum State {
	ANDHRA_PRADESH("ANDHRA PRADESH"),
	ARUNACHAL_PRADESH("ARUNACHAL PRADESH"),
	ASSAM("ASSAM"),
	BIHAR("BIHAR"),
	CHHATTISGARH("CHHATTISGARH"),
	GOA("GOA"),
	GUJARAT("GUJARAT"),
	HARYANA("HARYANA"),
	HIMACHAL_PRADESH("HIMACHAL PRADESH"),
	JAMMU_AND_KASHMIR("JAMMU AND KASHMIR"),
	JHARKHAND("JHARKHAND"),
	KARNATAKA("KARNATAKA"),
	KERALA("KERALA"),
	MADHYA_PRADESH("MADHYA PRADESH"),
	MAHARASHTRA("MAHARASHTRA"),
	MANIPUR("MANIPUR"),
	MEGHALAYA("MEGHALAYA"),
	MIZORAM("MIZORAM"),
	NAGALAND("NAGALAND"),
	ODISHA("ODISHA"),
	PUNJAB("PUNJAB"),
	RAJASTHAN("RAJASTHAN"),
	SIKKIM("SIKKIM"),
	TAMIL_NADU("TAMIL NADU"),
	TELANGANA("TELANGANA"),
	TRIPURA("TRIPURA"),
	UTTAR_PRADESH("UTTAR PRADESH"),
	UTTARAKHAND("UTTARAKHAND"),
	WEST_BENGAL("WEST BENGAL");
		
	private String state;

	private State(String state) {
		this.state = state;
	}

	public String getState() {
		return this.state;
	}

}
